loki:
  resources:
    requests:
      cpu: 10m
      memory: 294Mi
    limits:
      memory: 294Mi

promtail:
  resources:
    requests:
      cpu: 17m
      memory: 118Mi
    limits:
      memory: 118Mi
