# Based on https://github.com/viaduct-ai/kustomize-sops?tab=readme-ov-file#3-configure-sops-via-sopsyaml

creation_rules:
  - azure_keyvault: https://equalvote.vault.azure.net/keys/sops/92a0fe05a77b4a3787d10bbd444f19c6
    path_regex: secret.*\.yaml(.dec)?$
    unencrypted_regex: "^(apiVersion|metadata|kind|type)$"
