apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "bootstrap-secrets"
  namespace: "argocd"
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
spec:
  project: "default"
  source:
    repoURL: "https://github.com/Equal-Vote/argocd.git"
    targetRevision: "HEAD"
    path: "secrets"
  destination:
    name: "in-cluster"
    namespace: "argocd"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "bootstrap-cluster"
  namespace: "argocd"
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
spec:
  project: "default"
  source:
    repoURL: "https://github.com/Equal-Vote/argocd.git"
    targetRevision: "HEAD"
    path: "applications"
  destination:
    name: "in-cluster"
    namespace: "argocd"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "cert-manager"
  namespace: "argocd"
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
spec:
  project: "default"
  sources:
    - repoURL: "https://charts.jetstack.io"
      targetRevision: "1.20.1"
      chart: "cert-manager"
      helm:
        valueFiles:
          - "$values/applications/cert-manager/values.yaml"
    - repoURL: "https://github.com/Equal-Vote/argocd.git"
      ref: "values"
      targetRevision: "HEAD"
  destination:
    name: "in-cluster"
    namespace: "cert-manager"
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
    syncOptions:
      - CreateNamespace=true
