apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap
spec:
  destination:
    name: https://kubernetes.default.svc
    namespace: argocd
  source:
    path: apps
    repoURL: https://github.com/Equal-Vote/argocd.github
    targetRevision: HEAD
  project: default
