apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "bootstrap-secrets"
  namespace: "argocd"
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
spec:
  project: "default"
  source:
    repoURL: "https://github.com/Equal-Vote/argocd.git"
    targetRevision: "HEAD"
    path: "secrets"
  destination:
    name: "in-cluster"
    namespace: "argocd"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "bootstrap-cluster"
  namespace: "argocd"
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
spec:
  project: "default"
  source:
    repoURL: "https://github.com/Equal-Vote/argocd.git"
    targetRevision: "HEAD"
    path: "applications"
  destination:
    name: "in-cluster"
    namespace: "argocd"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
