# We can't monitor the Azure AKS control plane services
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false

nodeExporter:
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      memory: 100Mi
kube-state-metrics:
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      memory: 100Mi
prometheusOperator:
  resources:
    requests:
      cpu: 10m
      memory: 323Mi
    limits:
      memory: 323Mi
alertmanager:
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      memory: 100Mi
  config:
    route:
      # Uncomment this if alerts are too spammy.
      # group_by: ["alertname"]
      receiver: "slack"

      # Configuring some alerts to go into the void...
      routes:
      - receiver: 'null'
        matchers:
          - alertname = "InfoInhibitor"
      - receiver: 'null'
        matchers:
          - alertname = "Watchdog"

    receivers:
    - name: "null"
    - name: "slack"
      # https://prometheus.io/docs/alerting/latest/configuration/#slack_config
      slack_configs:
      - api_url_file: /etc/alertmanager/secrets/alertmanager-slack/slack_webhook_url
        channel: "#_bettervoting"
        send_resolved: true
        # TODO: Should we enable this?
        # https://prometheus.io/docs/alerting/latest/notification_examples/#ranging-over-all-received-alerts
        # title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        # text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
  alertmanagerSpec:
    secrets:
    - alertmanager-slack
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/auth-type: "basic"
      nginx.ingress.kubernetes.io/auth-secret: "basic-auth"
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    hosts:
    - alertmanager.prod.equal.vote
    tls:
    - secretName: alertmanager-tls
      hosts:
      - alertmanager.prod.equal.vote
prometheus:
  prometheusSpec:
    storage:
      enabled: true
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/auth-type: "basic"
      nginx.ingress.kubernetes.io/auth-secret: "basic-auth"
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    hosts:
    - prometheus.prod.equal.vote
    tls:
    - secretName: prometheus-tls
      hosts:
      - prometheus.prod.equal.vote
grafana:
  resources:
    requests:
      cpu: 10m
      memory: 384Mi
    limits:
      memory: 384Mi
  admin:
    existingSecret: grafana
  additionalDataSources:
  - name: loki
    type: loki
    url: http://loki.loki:3100
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
    - grafana.prod.equal.vote
    tls:
    - secretName: grafana-tls
      hosts:
      - grafana.prod.equal.vote
