kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false

defaultRules:
  rules:
    kubernetesResources: false
  disabled:
    InfoInhibitor: true
    KubeVersionMismatch: true

alertmanager:
  config:
    route:
      # Uncomment this if alerts are too spammy.
      # group_by: ["alertname"]
      receiver: "slack"
    receivers:
    - name: "null"
    - name: "slack"
      # https://prometheus.io/docs/alerting/latest/configuration/#slack_config
      slack_configs:
      - api_url_file: /etc/prometheus-secrets/alertmanager-slack/slack_webhook_url
        channel: "#_bettervoting"
        send_resolved: true
        # TODO: Should we enable this?
        # https://prometheus.io/docs/alerting/latest/notification_examples/#ranging-over-all-received-alerts
        # title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        # text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
  secretMounts:
  - name: alertmanager-slack
    secretName: alertmanager-slack
    mountPath: /etc/prometheus-secrets/alertmanager-slack
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/auth-type: "basic"
      nginx.ingress.kubernetes.io/auth-secret: "basic-auth"
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    hosts:
    - alertmanager.prod.equal.vote
    tls:
    - secretName: alertmanager-tls
      hosts:
      - alertmanager.prod.equal.vote

prometheus:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/auth-type: "basic"
      nginx.ingress.kubernetes.io/auth-secret: "basic-auth"
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    hosts:
    - prometheus.prod.equal.vote
    tls:
    - secretName: prometheus-tls
      hosts:
      - prometheus.prod.equal.vote

grafana:
  admin:
    existingSecret: grafana
  additionalDataSources:
  - name: loki
    type: loki
    url: http://loki:3100
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
    - grafana.prod.equal.vote
    tls:
    - secretName: grafana-tls
      hosts:
      - grafana.prod.equal.vote
