kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false

defaultRules:
  rules:
    kubernetesResources: false
  disabled:
    InfoInhibitor: true
    KubeVersionMismatch: true

alertmanager:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/auth-type: "basic"
      nginx.ingress.kubernetes.io/auth-secret: "alertmanager-auth"
      nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - am"
    hosts:
    - alertmanager.sandbox.star.vote
    tls:
    - secretName: alertmanager-tls
      hosts:
      - alertmanager.sandbox.star.vote

prometheus:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/auth-type: "basic"
      nginx.ingress.kubernetes.io/auth-secret: "prometheus-auth"
      nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - prom"
    hosts:
    - prometheus.sandbox.star.vote
    tls:
    - secretName: prometheus-tls
      hosts:
      - prometheus.sandbox.star.vote

grafana:
  additionalDataSources:
  - access: proxy
    isDefault: false
    name: loki
    orgId: 1
    type: loki
    url: http://loki:3100
    version: 1
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
    - grafana.sandbox.star.vote
    tls:
    - secretName: grafana-tls
      hosts:
      - grafana.sandbox.star.vote
