replicaCount: 2
image:
  repository: ghcr.io/equal-vote/star-server
  tag: "sha-82f746d"
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
  hosts:
    - host: bettervoting.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: star-server-tls
      hosts:
        - bettervoting.com
        - www.bettervoting.com
env:
  - name: ALLOWED_URLS
    value: "http://localhost:3000/"
  - name: DEV_DATABASE
    value: "TRUE"
  - name: KEYCLOAK_PUBLIC_KEY
    value: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqtpqT6UqfEFk/Bw6LVzkFH+5VYtzhL9mlAY7UIpeHJQWo4hQ9NP0A9V2YQVdvl4hz5f7Kol6oqP4+CdbRCBDjJ+USWntmJvnXlVdDcHrC4ZtU/39FTmr3ZTxlMbFksz9SRYJLJRazsR/GU3Ropg9lOjvMm0KWlrbgk7pxX70LcPfXQ3Pa4dlKRe57gUn8GNr7gA0qU0ctDob0MSEQFO27FCiRDLigMTm8Uj/KD7avZUplNfkrLnKX90mfE7ESOY8DJBJcA7hZwv522XvtMXDb0xcNwgDrvEvgNbZqbE5VP/Iadip210LTnb40fIP+iECMbsXxw38lkQ/7UQzreK5ewIDAQAB"
  - name: S3_ID
    value: "AKIA4DAHQS5EADVYNTUP"
  - name: KEYCLOAK_URL
    value: "http://keycloak.keycloak.svc.cluster.local/realms/Prod/protocol/openid-connect"
  - name: REACT_APP_KEYCLOAK_URL
    value: "https://keycloak.prod.equal.vote/realms/Prod/protocol/openid-connect"
  - name: REACT_APP_SOCKET_URL
    value: https://bettervoting.com
  - name: REACT_APP_BACKEND_URL
    value: http://localhost:5000
  - name: REACT_APP_FEATURED_ELECTIONS
    value: "4e7b3f9d-ce53-4b25-8747-b5927c6745aa,753bb873-12de-4aca-af25-e96ec72f0b49,18ad9f37-94a8-4fed-a784-83761c692052"
  - name: REACT_APP_MAX_BALLOT_RANKS
    value: "8"
  - name: REACT_APP_DEFAULT_BALLOT_RANKS
    value: "6"
  - name: SENDGRID_GROUP_ID
    value: "43160"
  - name: FROM_EMAIL_ADDRESS
    value: "elections@star.vote"
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: star-server
        key: DATABASE_URL
  - name: SENDGRID_API_KEY
    valueFrom:
      secretKeyRef:
        name: star-server
        key: SENDGRID_API_KEY
  - name: KEYCLOAK_SECRET
    valueFrom:
      secretKeyRef:
        name: star-server
        key: KEYCLOAK_SECRET
  - name: S3_SECRET
    valueFrom:
      secretKeyRef:
        name: star-server
        key: S3_SECRET
service:
  port: 5000
livenessProbe:
  httpGet:
    port: 5000
readinessProbe:
  httpGet:
    port: 5000
