image:
  repository: ghcr.io/equal-vote/star-server
  tag: "sha-b0c10c5"
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: star.sandbox.star.vote
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: star-server-tls
      hosts:
        - star.sandbox.star.vote
env:
  - name: ALLOWED_URLS
    value: "http://localhost:3000/"
  - name: DEV_DATABASE
    value: "TRUE"
  - name: KEYCLOAK_PUBLIC_KEY
    value: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqtpqT6UqfEFk/Bw6LVzkFH+5VYtzhL9mlAY7UIpeHJQWo4hQ9NP0A9V2YQVdvl4hz5f7Kol6oqP4+CdbRCBDjJ+USWntmJvnXlVdDcHrC4ZtU/39FTmr3ZTxlMbFksz9SRYJLJRazsR/GU3Ropg9lOjvMm0KWlrbgk7pxX70LcPfXQ3Pa4dlKRe57gUn8GNr7gA0qU0ctDob0MSEQFO27FCiRDLigMTm8Uj/KD7avZUplNfkrLnKX90mfE7ESOY8DJBJcA7hZwv522XvtMXDb0xcNwgDrvEvgNbZqbE5VP/Iadip210LTnb40fIP+iECMbsXxw38lkQ/7UQzreK5ewIDAQAB"
  - name: S3_ID
    value: "AKIA4DAHQS5EADVYNTUP"
  - name: KEYCLOAK_URL
    value: "http://keycloak.keycloak.svc.cluster.local/realms/Dev/protocol/openid-connect"
  - name: REACT_APP_KEYCLOAK_URL
    value: "https://keycloak.sandbox.star.vote/realms/Dev/protocol/openid-connect"
  - name: REACT_APP_TITLE
    value: "star.sandbox.star.vote"
  - name: REACT_APP_FEATURED_ELECTIONS
    value: "4tjgxk"
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: star-server
        key: DATABASE_URL
  - name: SENDGRID_API_KEY
    valueFrom:
      secretKeyRef:
        name: star-server
        key: SENDGRID_API_KEY
  - name: KEYCLOAK_SECRET
    valueFrom:
      secretKeyRef:
        name: star-server
        key: KEYCLOAK_SECRET
  - name: S3_SECRET
    valueFrom:
      secretKeyRef:
        name: star-server
        key: S3_SECRET
service:
  port: 5000
livenessProbe:
  httpGet:
    port: 5000
readinessProbe:
  httpGet:
    port: 5000
