# dyff between <(yq . <(helm show values oci://quay.io/jetstack/charts/cert-manager --version v1.20.0)) <(yq eval '. * load("values.yaml")' <(helm show values oci://quay.io/jetstack/charts/cert-manager --version v1.20.0))
# vim -O <(helm show values oci://quay.io/jetstack/charts/cert-manager --version v1.20.0) values.yaml

# CRDs have already been installed in this cluster, so we don't need to do this again.
# crds:
#   enabled: true

# ArgoCD keeps recreating the startupapicheck job, which appears to be passing. It's stuck in a loop. So, we're just going to disable it here.
startupapicheck:
  enabled: false

podLabels:
  azure.workload.identity/use: "true"
serviceAccount:
  labels:
    azure.workload.identity/use: "true"

# Commenting out for now to see if this is what's causing the deploy problem.
# resources:
#   requests:
#     cpu: 10m
#     memory: 100Mi
#   limits:
#     memory: 100Mi
# cainjector:
#   resources:
#     requests:
#       cpu: 10m
#       memory: 100Mi
#     limits:
#       memory: 100Mi
# webhook:
#   resources:
#     requests:
#       cpu: 10m
#       memory: 100Mi
#     limits:
#       memory: 100Mi
