controller:
# Newer charts seem to establish externalTrafficPolicy to Cluster instead of Local, breaks in Azure
# https://github.com/kubernetes/ingress-nginx/issues/10863
  service:
    externalTrafficPolicy: "Local"
  ingressClassResource:
    default: true
  replicaCount: 2
