config:
  outputs: |
    [OUTPUT]
        Name                 loki
        Match                kube.*
        Host                 loki.loki.svc.cluster.local
        Port                 3100
        Labels               job=fluent-bit
        Auto_Kubernetes_Labels on
        Line_Format          json

    [OUTPUT]
        Name                 loki
        Match                host.*
        Host                 loki.loki.svc.cluster.local
        Port                 3100
        Labels               job=fluent-bit-host
        Line_Format          json

resources:
  requests:
    cpu: 10m
    memory: 100Mi
  limits:
    memory: 100Mi
