kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false

defaultRules:
  rules:
    kubernetesResources: false
  disabled:
    InfoInhibitor: true
    KubeVersionMismatch: true

alertmanager:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/auth-type: "basic"
      nginx.ingress.kubernetes.io/auth-secret: "alertmanager-auth"
      nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - am"
    hosts:
    - alertmanager.prod.equal.vote
    tls:
    - secretName: alertmanager-tls
      hosts:
      - alertmanager.prod.equal.vote

prometheus:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/auth-type: "basic"
      nginx.ingress.kubernetes.io/auth-secret: "prometheus-auth"
      nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - prom"
    hosts:
    - prometheus.prod.equal.vote
    tls:
    - secretName: prometheus-tls
      hosts:
      - prometheus.prod.equal.vote

grafana:
  additionalDataSources:
  - name: loki
    type: loki
    url: http://loki:3100
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
    - grafana.prod.equal.vote
    tls:
    - secretName: grafana-tls
      hosts:
      - grafana.prod.equal.vote
