# https://kubernetes-sigs.github.io/external-dns/v0.14.0/tutorials/azure/#creating-an-azure-dns-zone
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    chart: external-dns
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.14.3
    helm:
      releaseName: external-dns
      values: |
        provider: azure
        secretConfiguration:
          enabled: true
          mountPath: "/etc/kubernetes/"
          data:
            azure.json: |
              {
                "subscriptionId": "86f3145a-48cc-4255-8757-dd3104d15e57",
                "resourceGroup": "equalvote",
                "useWorkloadIdentityExtension": true
              }
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
