# https://artifacthub.io/packages/helm/bitnami/keycloak
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    chart: keycloak
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 18.7.0
    helm:
      releaseName: keycloak
      # TODO: we'll define values/volume here to import realm settings according to the documentation
      # https://github.com/bitnami/charts/tree/main/bitnami/keycloak#importing-and-exporting-a-realm
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
