apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matomo
  namespace: argocd
spec:
  project: default
  source:
    chart: matomo
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 3.2.2
    helm:
      releaseName: matomo
      values: |
        ingress:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: matomo
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
