# https://artifacthub.io/packages/helm/bitnami/matomo
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matomo
  namespace: argocd
spec:
  project: default
  source:
    chart: matomo
    repoURL: https://github.com/bitnami/charts/tree/main/bitnami/matomo/
    targetRevision: 7.0.3
    helm:
      releaseName: matomo
  destination:
    server: https://kubernetes.default.svc
    namespace: matomo
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
