apiVersion: v1
kind: Secret
metadata:
    name: fider
    namespace: fider
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:z8oDtWAbaAK5aF1gmgErC6KXNyzbziVI019w4sszR9TA+IXS2tfa4SNoIQJS6iGHGGtR7AZHSPd0uk5gnQn+CQ==,iv:v9WnE2pFjiSZ85qGCL2baseZv62e+9hgneij2SENbFo=,tag:Dh7pl0Ur+bxZgxrYnGFLgA==,type:str]
    EMAIL_SMTP_PASSWORD: ENC[AES256_GCM,data:fSOZZ13faAghsWiH5FzGY8BYvLp/Zd5trsclqtxm2/3nKd7KaNULinYwV40VRuBWKA4uMCUdEYrZ/gwzMr2EXzK5q5gC,iv:OY8BZTQupVmA24MrBkasuCn/Z7kV15SftGank/iuAUM=,tag:F/HlwoRwtLKw24UybLd3og==,type:str]
sops:
    azure_kv:
        - created_at: "2026-06-20T01:23:30Z"
          enc: UK0lWszEIBPRxP4L1GFs2wlcVbSS_-JVDkEnQ1A5lXBoafHwdrdLyHtBP-XddyWNDILsnjuGUoyvlLVuMq80aavdsdGfx5ktZ5p2o9550fka50VzU_XpHBFbR_wsHUKb9ofhlok2SzwM_ZnpjWFDII_wvzZir9htaC4ALzQwE3ps4rsRgZP20e3_kHvsbw-v0vaOKo1fOdjPCn_Kl15ykuCT49Hfq2AGtVA1H6Ircip1DgvgFmixySF97KqjK2XWcdv1qVGL0UfJbChJJVOctgsIiHIH-6N3Hm2Z5ZQzU0oD3CPFp_C2lNk45yun3l7JSNhoeOMWTp2peXFX1Mo3Mg
          name: sops-key
          vault_url: https://equalvote-argocd.vault.azure.net
          version: 9d7a971e677f4d8a9f2f7adaf349f7ff
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T18:21:07Z"
    mac: ENC[AES256_GCM,data:IeF3EXsgHX4cXsNyYuNaiGyLFYowKmtWIBFN1HwBE4qgDbIUEjh4TcGscFut/BpiGicxGr8/lmJEe/hhKQo687hj6fEZ76nt7uhUcYE8IH18OSZtk0RQXv0oPKbjkc3YeLLNKVhUTcd1undhvGu0sfccBc84WzG+gmJEOcK5XTA=,iv:ewOGHB8LIde0j0BtVe92WGv8iM/Hz07Akl70eGBOquA=,tag:vejcKforXQaHx0znY+WXDQ==,type:str]
    version: 3.13.1
