apiVersion: v1
kind: Secret
metadata:
    name: fider-db-creds
    namespace: fider
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:j8Ixai0=,iv:1iB3n6HXIK9vq9BIvrmaKFbV8LgDk6tH1KYEWxWk/7Q=,tag:Pj/ptiF3CBCFAAttRl6jBg==,type:str]
    password: ENC[AES256_GCM,data:DOOkDcxKmQ7PKJH54f47cOg1YAVykqUFlBxx8X7ZHf8=,iv:FRTSqejXiDW5ndyAxnXYnpE95E+5agx792FuvOPrAto=,tag:90ZnqxJLqKYcBJlT7P11Gg==,type:str]
sops:
    azure_kv:
        - created_at: "2026-08-19T19:04:44Z"
          enc: FOhkcdMx5B6S5UlHs9AZOmIiHN7Pxxemij1oahFfhNDq7VGLu4qodPAOdZO6Xx3Y3DcUjw71Hf6bkWMYfzIGwJwyY-gp-r4odvaXh5DuHneLg_EWqOEd39wB1rO88roxLpVtPNPMt4kTfFQavqOoNk1DTdwyhmDZK2wPsPeQWwqgzDpCaqpFnTQ3okvVpWaXyTsqQCQ2c25ekzBjdBo2XkxthgrAzopNF3tzwdMLNX9ZdhR1JXqkkPQuvh2i15PanfuEWN1PVzmQk72Sc7vYRRNOoa2nuMCx3dp9LgxlLDQdoYtv05431LnN6byp995gGgVHNU_LE72Yd_09hUFj5Q
          name: sops-key
          vault_url: https://equalvote-argocd.vault.azure.net
          version: 9d7a971e677f4d8a9f2f7adaf349f7ff
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T19:04:46Z"
    mac: ENC[AES256_GCM,data:y+zXzYx7cES0/VGE3SojMxKOdb5aM54rGW0cjjboQnkh1LAQnGpLxeqCpWasPE3d7HyFWmGD410SMK542RJwlRUnPGnO/Sv28E3CbdnOvT9MMxaq3DGhCDChspx+Q4wcaLGUoXP8KnObPI9XslhLUN8syoVzmlq+fHRHAzbPRsI=,iv:ha/7607QPC10D6CPsjiHgjuucWVsFg5YSreDB6+C1v8=,tag:d+xO6StO9Lu3Dz7TtK18Yg==,type:str]
    version: 3.13.3
