apiVersion: v1
kind: Secret
metadata:
    name: fider
    namespace: fider
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:dpCkxrw4J1y+6W8onSaaMyufLdhoR9G5X+sdXjx+3o2pLWAulRx71z4ZhyutbGaYCSCzyuFJhjHYEgfYYxYyRQvcpO3gB1AvvAVzf/0xntsWvhKNnfi9eA==,iv:XfLFQwP8t49jwgw5pYaqFQVFBYZ1Es5ZrCuYPB7O2gM=,tag:VEAquZXarlLMR4RiC42/xA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:z8oDtWAbaAK5aF1gmgErC6KXNyzbziVI019w4sszR9TA+IXS2tfa4SNoIQJS6iGHGGtR7AZHSPd0uk5gnQn+CQ==,iv:v9WnE2pFjiSZ85qGCL2baseZv62e+9hgneij2SENbFo=,tag:Dh7pl0Ur+bxZgxrYnGFLgA==,type:str]
    EMAIL_SMTP_PASSWORD: ENC[AES256_GCM,data:fSOZZ13faAghsWiH5FzGY8BYvLp/Zd5trsclqtxm2/3nKd7KaNULinYwV40VRuBWKA4uMCUdEYrZ/gwzMr2EXzK5q5gC,iv:OY8BZTQupVmA24MrBkasuCn/Z7kV15SftGank/iuAUM=,tag:F/HlwoRwtLKw24UybLd3og==,type:str]
sops:
    azure_kv:
        - created_at: "2026-06-20T01:23:30Z"
          enc: UK0lWszEIBPRxP4L1GFs2wlcVbSS_-JVDkEnQ1A5lXBoafHwdrdLyHtBP-XddyWNDILsnjuGUoyvlLVuMq80aavdsdGfx5ktZ5p2o9550fka50VzU_XpHBFbR_wsHUKb9ofhlok2SzwM_ZnpjWFDII_wvzZir9htaC4ALzQwE3ps4rsRgZP20e3_kHvsbw-v0vaOKo1fOdjPCn_Kl15ykuCT49Hfq2AGtVA1H6Ircip1DgvgFmixySF97KqjK2XWcdv1qVGL0UfJbChJJVOctgsIiHIH-6N3Hm2Z5ZQzU0oD3CPFp_C2lNk45yun3l7JSNhoeOMWTp2peXFX1Mo3Mg
          name: sops-key
          vault_url: https://equalvote-argocd.vault.azure.net
          version: 9d7a971e677f4d8a9f2f7adaf349f7ff
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T17:17:37Z"
    mac: ENC[AES256_GCM,data:DgC+8AOIEnIs6oVWQ00qjvslmIYEnMTzMF6ZASeNUYAKlRM3PxVNNmmMLDYQ+3xWKBGxzuSlBgaCBG2xjzjLL9suxzkTccVu9GMWhfCfq5CQR8qEqy+ssoSUI/q73Dts9Hog4gg+PjDRqgXF1Pmp6kZOwyUmFtDfVeYi7U5gbsc=,iv:6+hAfDQ8nssrDPQ9vJP2LSU53sUO8+ZCfVE4R7CwWNk=,tag:cz/v5aNF8vMhbjq9LRIXAw==,type:str]
    version: 3.13.1
