apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "keycloak"
---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "starvote"
---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "kube-prometheus-stack"
---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "discord-bot"
