apiVersion: v1
kind: Secret
metadata:
    name: keycloak
    namespace: keycloak
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:AGsQBeAqEPL9HXGNGGLkxPKmHaSNttNuh6mt+g==,iv:Urp0jYF3vLf0pTUPxeWmDmSLVdYrMhln/MDjsiTMnog=,tag:lUZJEHoEsh0mYn2HF1JlrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://equalvote-argocd.vault.azure.net
          name: sops-key
          version: 9d7a971e677f4d8a9f2f7adaf349f7ff
          created_at: "2024-04-24T06:27:58Z"
          enc: qPzEt-V5mhNjscq5dTHnu5F2ocE8EnYhQvNAVVA0vwB67ZbK-wwVzChw1IwAtXTvppsjXAANN8x6zulORC9MXNOWqYVTcZsXdahDY9A7yrkjOkEmKbc-Vo0c1I992rZAiRbZipgMkr3-vYAc8TvHe70BlwbKqy1RoYfdZncqpDfmagksP7kCownPmu6i6p3GTfKvRYDikJzHiGMwQTNQWAkDyNUNG8-z3DPjn9ONmHv0i1LSvAG5pDwgJFWweiZuSR-nRDo-X0qdijDneQEZz24fKc22fMh2fsfULkoqckOTR53cDJxg1y5zhBY17Zi7JavTEnWsHDRBui0lsmytdQ
    hc_vault: []
    age: []
    lastmodified: "2024-04-24T06:28:01Z"
    mac: ENC[AES256_GCM,data:uNDJDHvf7ooYwKzB6YgjAYqrgq44EVNlT6e0oA9mskS4RXxviET0dE7IZ/bbsnfVsaDuKt9iHX+zyi49efqlzp2T62w8j2T+Mwx0vdSO9k1eSxUEF7byTbaZpeJ7AYcJ2DhYEPyNcxMO98CJCmb7CUraRQVycFMtckYf1PnKGOQ=,iv:3vGQoBWs0SImmqPHUYM53g51/Z1cnWBf5GpyuOEDrdM=,tag:6ci5wqcyAiLAERsdxs/o4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-postgresql
    namespace: keycloak
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:KiQvxZuP/1AdqiLvIfoR6AS8HjaIHUbxoUZEdg==,iv:ZNzHTzuAn59JPLGPBK+dmL8K2HI5PCcCQuNqvj7OCxc=,tag:oeU84zSIypeFhBPvlvQXhA==,type:str]
    postgres-password: ENC[AES256_GCM,data:iARRU2f2FN68gSfNGBPoUndNOY+g2rdl8fzE9A==,iv:kVaQUnkhZc6d4+6tWKSpWoVC8V7ObgDeBGew5cOil0I=,tag:/cIKznWylnVlojYrmam09w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://equalvote-argocd.vault.azure.net
          name: sops-key
          version: 9d7a971e677f4d8a9f2f7adaf349f7ff
          created_at: "2024-04-24T06:27:58Z"
          enc: qPzEt-V5mhNjscq5dTHnu5F2ocE8EnYhQvNAVVA0vwB67ZbK-wwVzChw1IwAtXTvppsjXAANN8x6zulORC9MXNOWqYVTcZsXdahDY9A7yrkjOkEmKbc-Vo0c1I992rZAiRbZipgMkr3-vYAc8TvHe70BlwbKqy1RoYfdZncqpDfmagksP7kCownPmu6i6p3GTfKvRYDikJzHiGMwQTNQWAkDyNUNG8-z3DPjn9ONmHv0i1LSvAG5pDwgJFWweiZuSR-nRDo-X0qdijDneQEZz24fKc22fMh2fsfULkoqckOTR53cDJxg1y5zhBY17Zi7JavTEnWsHDRBui0lsmytdQ
    hc_vault: []
    age: []
    lastmodified: "2024-04-24T06:28:01Z"
    mac: ENC[AES256_GCM,data:uNDJDHvf7ooYwKzB6YgjAYqrgq44EVNlT6e0oA9mskS4RXxviET0dE7IZ/bbsnfVsaDuKt9iHX+zyi49efqlzp2T62w8j2T+Mwx0vdSO9k1eSxUEF7byTbaZpeJ7AYcJ2DhYEPyNcxMO98CJCmb7CUraRQVycFMtckYf1PnKGOQ=,iv:3vGQoBWs0SImmqPHUYM53g51/Z1cnWBf5GpyuOEDrdM=,tag:6ci5wqcyAiLAERsdxs/o4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
