apiVersion: v1
kind: Secret
metadata:
    name: keycloak
    namespace: keycloak
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:31VfKhIiJ2rSP5nYegHhjHqyBerLXg7TPbs27w==,iv:BLg81Gb/UT0RMx/1DM6po2NscTNFB7dVDSSfTqZSJY0=,tag:yyFE4baZvhqgBKmYfVM1Ig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://equalvote-argocd.vault.azure.net
          name: sops-key
          version: 9d7a971e677f4d8a9f2f7adaf349f7ff
          created_at: "2024-05-07T05:05:04Z"
          enc: QOBgOqlmvBT2NkHcf2C88dj7kJ5z741odYD2OsEK5ExKxtjUXXbsO5TQJ9FTJqpkIpKbRwhr5hmSd4PRb7lBS-5e5NXHPcJZf3WlQRqCMN4J9nYRXvJ6IL8fgFc4zMst7tAqO92znka8hNnbrfo53JCf1XLcehkqxC7Ju4iCMe0RACq7_jLudNipEg-snWcyCqbOzxqmNeUel_XnrH5kdB0ko2IkJQ95t6DkKMxfT1FFNrp17Wb3E95INuMLTihsV4Xx0lHzp82AvAX-H5BmLS3Wt4HBtzOqPmw8neE9_u7_lvLCYqfBiIxBmSMY_FRK6HQwqWLFqBWaihIx627Fqw
    hc_vault: []
    age: []
    lastmodified: "2024-05-07T05:05:06Z"
    mac: ENC[AES256_GCM,data:QMDo2CE9Yji4o2rlCCZIpHZWNrXBfxMxR/iO/3MV7StEiH+h/wrN4zFZzr6a8EYfosLk12XN8aFTvvjAzCW0YYtfefqD0RB2j37GbijsSGUxHKbVvZJeZp4KK25rCa6lXrKsQruIYUX9HDTmiYcvgWsNz6TwkIYfkAVPjZg4eWw=,iv:fN3kbkOGQvWg1IjV2HiR/+R6Vw4ljB/AAL4X54DRUz8=,tag:VrMKPVKXQ7KWKfxrjwfQHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-postgresql
    namespace: keycloak
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:R5XAnWJCUhoi9iR6X6QfLqex5NRMtZXAreuJZw==,iv:uoC77h4mCSFo475WVUnAg8y2B4Eg5WTLUKsO9i10Qj4=,tag:aPj6VItZxHqXL+bSyugOjw==,type:str]
    postgres-password: ENC[AES256_GCM,data:AX4m/1NbqNOXphkk/318FvRAoVXzJaUIusV4ZA==,iv:ZDJtoMg6o2U39ll/S76ieGlfDjQsAT2kNNq6IargBjk=,tag:XCoOK64ETFf+ooFUrR3IRA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://equalvote-argocd.vault.azure.net
          name: sops-key
          version: 9d7a971e677f4d8a9f2f7adaf349f7ff
          created_at: "2024-05-07T05:05:04Z"
          enc: QOBgOqlmvBT2NkHcf2C88dj7kJ5z741odYD2OsEK5ExKxtjUXXbsO5TQJ9FTJqpkIpKbRwhr5hmSd4PRb7lBS-5e5NXHPcJZf3WlQRqCMN4J9nYRXvJ6IL8fgFc4zMst7tAqO92znka8hNnbrfo53JCf1XLcehkqxC7Ju4iCMe0RACq7_jLudNipEg-snWcyCqbOzxqmNeUel_XnrH5kdB0ko2IkJQ95t6DkKMxfT1FFNrp17Wb3E95INuMLTihsV4Xx0lHzp82AvAX-H5BmLS3Wt4HBtzOqPmw8neE9_u7_lvLCYqfBiIxBmSMY_FRK6HQwqWLFqBWaihIx627Fqw
    hc_vault: []
    age: []
    lastmodified: "2024-05-07T05:05:06Z"
    mac: ENC[AES256_GCM,data:QMDo2CE9Yji4o2rlCCZIpHZWNrXBfxMxR/iO/3MV7StEiH+h/wrN4zFZzr6a8EYfosLk12XN8aFTvvjAzCW0YYtfefqD0RB2j37GbijsSGUxHKbVvZJeZp4KK25rCa6lXrKsQruIYUX9HDTmiYcvgWsNz6TwkIYfkAVPjZg4eWw=,iv:fN3kbkOGQvWg1IjV2HiR/+R6Vw4ljB/AAL4X54DRUz8=,tag:VrMKPVKXQ7KWKfxrjwfQHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: postgresql
    namespace: starvote
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:fF5zOhm0dfaOksMyTJ/skmtvWI0=,iv:vPf7XBQjkV04ozJYBVp7bT/pUg7qnJGrMdcSJta2bBw=,tag:3W11sIreVXgcwkOAJ6X4Fg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://equalvote-argocd.vault.azure.net
          name: sops-key
          version: 9d7a971e677f4d8a9f2f7adaf349f7ff
          created_at: "2024-05-07T05:05:04Z"
          enc: QOBgOqlmvBT2NkHcf2C88dj7kJ5z741odYD2OsEK5ExKxtjUXXbsO5TQJ9FTJqpkIpKbRwhr5hmSd4PRb7lBS-5e5NXHPcJZf3WlQRqCMN4J9nYRXvJ6IL8fgFc4zMst7tAqO92znka8hNnbrfo53JCf1XLcehkqxC7Ju4iCMe0RACq7_jLudNipEg-snWcyCqbOzxqmNeUel_XnrH5kdB0ko2IkJQ95t6DkKMxfT1FFNrp17Wb3E95INuMLTihsV4Xx0lHzp82AvAX-H5BmLS3Wt4HBtzOqPmw8neE9_u7_lvLCYqfBiIxBmSMY_FRK6HQwqWLFqBWaihIx627Fqw
    hc_vault: []
    age: []
    lastmodified: "2024-05-07T05:05:06Z"
    mac: ENC[AES256_GCM,data:QMDo2CE9Yji4o2rlCCZIpHZWNrXBfxMxR/iO/3MV7StEiH+h/wrN4zFZzr6a8EYfosLk12XN8aFTvvjAzCW0YYtfefqD0RB2j37GbijsSGUxHKbVvZJeZp4KK25rCa6lXrKsQruIYUX9HDTmiYcvgWsNz6TwkIYfkAVPjZg4eWw=,iv:fN3kbkOGQvWg1IjV2HiR/+R6Vw4ljB/AAL4X54DRUz8=,tag:VrMKPVKXQ7KWKfxrjwfQHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
