apiVersion: v1
kind: Secret
metadata:
    name: keycloak
    namespace: keycloak
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:9eaFY7yykfeR4Rzigr8YOb4IOnm+bl0npu2YXQ==,iv:/M+nXywPrLNmXeJy6yKYUS5nFrLLAgWLLdmWs2PimFQ=,tag:SJKLax/q0/ghCqlOoQgfiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://equalvote-argocd.vault.azure.net
          name: sops-key
          version: 9d7a971e677f4d8a9f2f7adaf349f7ff
          created_at: "2024-05-07T05:13:28Z"
          enc: p_r2qsbrmI32YS9wF_dKHsG1_RWuotYGbdRaM-7ModNNSMoUwZCo-6lSRBc1Y96qUIO62PaxrTNmKX3nMLD_WTf0whjJammznfFJKjmZdF9M0rZ4cIXRYvHZRk0fPGo-JZIskEtP1ntYkCn7ANQd8as0ZU7zOFqwu50C5XjrwMT1bIJp2Y12-_fu0aO20WVAdRJloBCj6jo4Os1pZnVNmeM0AshFl0q9mcdErURzj69uTVebtFMnMp0kIBCGc7IMZYkcSLqWRB6q3pDkY08Mpb_zcSvLRo5kzjEYafsKPEn7bIPjfbz6iO6c27r_HOv7hwqts_cr8zGA5-nVz4SK0A
    hc_vault: []
    age: []
    lastmodified: "2024-05-08T00:51:46Z"
    mac: ENC[AES256_GCM,data:b1zTNIuus/e4zHWVmUe+imLdLDZy8LFzQSohIFZTk6mrQsDfcOFSkvQCFkt2IDNiPulP1fHgjOSdEY+6Ug2fkAAGaprKDoY82THoba0/nrHnnSp0f4+b1K7JCfCNSNd3Sth6icKuPgmvq1BbVhzuvhqRqC3B/v9HFyjHD6jy0HM=,iv:GXxVlrH1mgQgYhtRrZHusdPcDuZA1aBhVWvKpMBYCjw=,tag:P/Vm7PxNrh0HZ/66weqddA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-postgresql
    namespace: keycloak
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:1eycVDaxpIKBHbkQYf+FqamDSfk2aHo28In19Q==,iv:f74UJe5mJ10JSIvnLmlJOCoJNhwHWcgiUMsc5oagC/0=,tag:HPRmhzMcubDVAN1zwrpUHg==,type:str]
    postgres-password: ENC[AES256_GCM,data:s5k3687v1PGpWbnNkh/Z2rND3DKA1ntp9g/XZg==,iv:leeWujBcgaauTQTcpqFJRj0Wv1AMAaWEueDADIbqjco=,tag:BoCbrvUohqjbgui18GWWeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://equalvote-argocd.vault.azure.net
          name: sops-key
          version: 9d7a971e677f4d8a9f2f7adaf349f7ff
          created_at: "2024-05-07T05:13:28Z"
          enc: p_r2qsbrmI32YS9wF_dKHsG1_RWuotYGbdRaM-7ModNNSMoUwZCo-6lSRBc1Y96qUIO62PaxrTNmKX3nMLD_WTf0whjJammznfFJKjmZdF9M0rZ4cIXRYvHZRk0fPGo-JZIskEtP1ntYkCn7ANQd8as0ZU7zOFqwu50C5XjrwMT1bIJp2Y12-_fu0aO20WVAdRJloBCj6jo4Os1pZnVNmeM0AshFl0q9mcdErURzj69uTVebtFMnMp0kIBCGc7IMZYkcSLqWRB6q3pDkY08Mpb_zcSvLRo5kzjEYafsKPEn7bIPjfbz6iO6c27r_HOv7hwqts_cr8zGA5-nVz4SK0A
    hc_vault: []
    age: []
    lastmodified: "2024-05-08T00:51:46Z"
    mac: ENC[AES256_GCM,data:b1zTNIuus/e4zHWVmUe+imLdLDZy8LFzQSohIFZTk6mrQsDfcOFSkvQCFkt2IDNiPulP1fHgjOSdEY+6Ug2fkAAGaprKDoY82THoba0/nrHnnSp0f4+b1K7JCfCNSNd3Sth6icKuPgmvq1BbVhzuvhqRqC3B/v9HFyjHD6jy0HM=,iv:GXxVlrH1mgQgYhtRrZHusdPcDuZA1aBhVWvKpMBYCjw=,tag:P/Vm7PxNrh0HZ/66weqddA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: postgresql
    namespace: starvote
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:S+2iJNqM4jPpsN0fY1DwQxcf8/hvL5AXHT3QlPSqeOTrt3P8ZbHcWw==,iv:CH6fAHG8iOhWuWYvp8hELJtg41xMTdL22+FFb756hew=,tag:CcrjHk9cQeUJJz7VPtnvXQ==,type:str]
    application: ENC[AES256_GCM,data:4/tVObj7t0rnKkJ0DJSMK7xIsg2S2s/mqXUL0DKWLR3xMPndJ7MMlw==,iv:2hUcixT2FgSPsX9eFLWnIYGy4fWQ71LG8TBZT58wV0U=,tag:DtY5t6dmGlvRdtLaOmT2iw==,type:str]
    replicator: ENC[AES256_GCM,data:uQFjSFIB7QtnPQBQV5b2Yxo+FpSuqZaB4IQq+tE/ZX5BaVQMv2yoCg==,iv:zk6LvHmGgfXqJ/ZLz+/RKGJlEOeCAAr3VFwTorcr2Pg=,tag:k9KMjGFQbZPoAarcTZTT4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://equalvote-argocd.vault.azure.net
          name: sops-key
          version: 9d7a971e677f4d8a9f2f7adaf349f7ff
          created_at: "2024-05-07T05:13:28Z"
          enc: p_r2qsbrmI32YS9wF_dKHsG1_RWuotYGbdRaM-7ModNNSMoUwZCo-6lSRBc1Y96qUIO62PaxrTNmKX3nMLD_WTf0whjJammznfFJKjmZdF9M0rZ4cIXRYvHZRk0fPGo-JZIskEtP1ntYkCn7ANQd8as0ZU7zOFqwu50C5XjrwMT1bIJp2Y12-_fu0aO20WVAdRJloBCj6jo4Os1pZnVNmeM0AshFl0q9mcdErURzj69uTVebtFMnMp0kIBCGc7IMZYkcSLqWRB6q3pDkY08Mpb_zcSvLRo5kzjEYafsKPEn7bIPjfbz6iO6c27r_HOv7hwqts_cr8zGA5-nVz4SK0A
    hc_vault: []
    age: []
    lastmodified: "2024-05-08T00:51:46Z"
    mac: ENC[AES256_GCM,data:b1zTNIuus/e4zHWVmUe+imLdLDZy8LFzQSohIFZTk6mrQsDfcOFSkvQCFkt2IDNiPulP1fHgjOSdEY+6Ug2fkAAGaprKDoY82THoba0/nrHnnSp0f4+b1K7JCfCNSNd3Sth6icKuPgmvq1BbVhzuvhqRqC3B/v9HFyjHD6jy0HM=,iv:GXxVlrH1mgQgYhtRrZHusdPcDuZA1aBhVWvKpMBYCjw=,tag:P/Vm7PxNrh0HZ/66weqddA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
data:
    auth: ENC[AES256_GCM,data:WVBKtoKpjwaZ+U2LPzumLgMqR5owjfGf3tNb6hATh8CLbvV9QHCoEM7SsLydVxuIufvBbRdowkFq9dUEeFT2CuYg6hI6dCTZhLofv2wd0tYr7ce8RbTnKw==,iv:97RwTyfren9TzxDPRSDWKJ47vdXSEfkY6gyEIH/KPn0=,tag:iGzLLY/g+gJ5D6ngMA7F0g==,type:str]
metadata:
    name: alertmanager-auth
    namespace: monitoring
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://equalvote-argocd.vault.azure.net
          name: sops-key
          version: 9d7a971e677f4d8a9f2f7adaf349f7ff
          created_at: "2024-05-07T05:13:28Z"
          enc: p_r2qsbrmI32YS9wF_dKHsG1_RWuotYGbdRaM-7ModNNSMoUwZCo-6lSRBc1Y96qUIO62PaxrTNmKX3nMLD_WTf0whjJammznfFJKjmZdF9M0rZ4cIXRYvHZRk0fPGo-JZIskEtP1ntYkCn7ANQd8as0ZU7zOFqwu50C5XjrwMT1bIJp2Y12-_fu0aO20WVAdRJloBCj6jo4Os1pZnVNmeM0AshFl0q9mcdErURzj69uTVebtFMnMp0kIBCGc7IMZYkcSLqWRB6q3pDkY08Mpb_zcSvLRo5kzjEYafsKPEn7bIPjfbz6iO6c27r_HOv7hwqts_cr8zGA5-nVz4SK0A
    hc_vault: []
    age: []
    lastmodified: "2024-05-08T00:51:46Z"
    mac: ENC[AES256_GCM,data:b1zTNIuus/e4zHWVmUe+imLdLDZy8LFzQSohIFZTk6mrQsDfcOFSkvQCFkt2IDNiPulP1fHgjOSdEY+6Ug2fkAAGaprKDoY82THoba0/nrHnnSp0f4+b1K7JCfCNSNd3Sth6icKuPgmvq1BbVhzuvhqRqC3B/v9HFyjHD6jy0HM=,iv:GXxVlrH1mgQgYhtRrZHusdPcDuZA1aBhVWvKpMBYCjw=,tag:P/Vm7PxNrh0HZ/66weqddA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
data:
    auth: ENC[AES256_GCM,data:yQagvTqlMhDoM3xklQoNOdH7Uxsx/E8vpOZCH5HJ429vvOcEUSX226MZQXMJ/rUBbyl4cLDf16py8lJdacFr8AHFpjTlTGCnqlVi2wm3rQsn/UUiH7lSrw==,iv:n2oYRdVD081eB5Up3i0MzJZT0Pm4aOvkdOy9j8MkGMo=,tag:w/guHNI541YT/Kdydz7J3g==,type:str]
kind: Secret
metadata:
    name: prometheus-auth
    namespace: monitoring
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://equalvote-argocd.vault.azure.net
          name: sops-key
          version: 9d7a971e677f4d8a9f2f7adaf349f7ff
          created_at: "2024-05-07T05:13:28Z"
          enc: p_r2qsbrmI32YS9wF_dKHsG1_RWuotYGbdRaM-7ModNNSMoUwZCo-6lSRBc1Y96qUIO62PaxrTNmKX3nMLD_WTf0whjJammznfFJKjmZdF9M0rZ4cIXRYvHZRk0fPGo-JZIskEtP1ntYkCn7ANQd8as0ZU7zOFqwu50C5XjrwMT1bIJp2Y12-_fu0aO20WVAdRJloBCj6jo4Os1pZnVNmeM0AshFl0q9mcdErURzj69uTVebtFMnMp0kIBCGc7IMZYkcSLqWRB6q3pDkY08Mpb_zcSvLRo5kzjEYafsKPEn7bIPjfbz6iO6c27r_HOv7hwqts_cr8zGA5-nVz4SK0A
    hc_vault: []
    age: []
    lastmodified: "2024-05-08T00:51:46Z"
    mac: ENC[AES256_GCM,data:b1zTNIuus/e4zHWVmUe+imLdLDZy8LFzQSohIFZTk6mrQsDfcOFSkvQCFkt2IDNiPulP1fHgjOSdEY+6Ug2fkAAGaprKDoY82THoba0/nrHnnSp0f4+b1K7JCfCNSNd3Sth6icKuPgmvq1BbVhzuvhqRqC3B/v9HFyjHD6jy0HM=,iv:GXxVlrH1mgQgYhtRrZHusdPcDuZA1aBhVWvKpMBYCjw=,tag:P/Vm7PxNrh0HZ/66weqddA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
